### PR TITLE
Style improvements

### PR DESCRIPTION
**Pull request by msachi**

### CODE REVIEW

**Comment by msachi** [comment]
Let me know what you think. I highlighted the suggested word, orange didn't work well so I changed it to blue (along with the nav bar). Needed to make the background of drop-down lighter grey.

**Comment by marisid** [comment]
Hey Marko! Blue looks better, we agree. We've added hover and focus pseudo classes for the suggested elements. We have also attached clickable listeners for the suggested elements so that the input field is updated based on the selected match :smile: What do you think? Esraa? Please merge!!!

**Comment by msachi** [comment]
Great, I was going to raise that as an issue! : ) The code looks good to me, wanna wait for Esraa or shall I merge?

**Comment by marisid** [comment]
I have no problem with merging Marko :smile: Shireen and I worked a little on the backend to clear the match array (we can discuss tomorrow)  but couldn't push our branch because the internet connection was rubbish in the library.  Let's have a look together tomorrow.  See ya at 11:) Enjoy your Saturday night!!

**Comment by msachi** [comment]
Ok but I'm not taking responsibility :P Sounds good, will see where we are tomorrow. Thanks, you too :)

**Pull request merged**
